'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class CatIngresos
End Class
